apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "clickhouse-ha"
  namespace: "clickhouse"
spec:
  configuration:
    files:
      ch-config.xml: |
        <clickhouse>
          <openSSL>
                  <server>
                      <certificateFile>/etc/clickhouse-server/certs/server.crt</certificateFile>
                      <privateKeyFile>/etc/clickhouse-server/certs/server.key</privateKeyFile>
                      <verificationMode>relaxed</verificationMode>
                      <loadDefaultCAFile>true</loadDefaultCAFile>
                      <cacheSessions>true</cacheSessions>
                      <disableProtocols>sslv2,sslv3</disableProtocols>
                      <preferServerCiphers>true</preferServerCiphers>
                  </server>
                  <client>
                      <loadDefaultCAFile>true</loadDefaultCAFile>
                      <caConfig>/etc/clickhouse-server/certs/ca.crt</caConfig>
                      <cacheSessions>true</cacheSessions>
                      <disableProtocols>sslv2,sslv3</disableProtocols>
                      <preferServerCiphers>true</preferServerCiphers>
                  </client>
              </openSSL>
          <listen_host>0.0.0.0</listen_host>
          <https_port>8443</https_port>
          <http_port>8123</http_port>
          <tcp_port_secure>9440</tcp_port_secure>
          <interserver_https_port>9010</interserver_https_port>
          <interserver_http_port remove="1"/>
        </clickhouse>
      server.crt:
            valueFrom:
              secretKeyRef:
                name: clickhouse-ssl-certs
                key: server.crt
      server.key:
        valueFrom:
          secretKeyRef:
            name: clickhouse-ssl-certs
            key: server.key
      ca.crt:
        valueFrom:
          secretKeyRef:
            name: clickhouse-ssl-certs
            key: server.key
    clusters:
      - name: "cluster-ha"
        secure: "yes"
        insecure: "no"
        layout:
          shardsCount: 1
          replicasCount: 1
        
    zookeeper:
      nodes:
        - host: zookeeper-0.zookeepers.clickhouse.svc.cluster.local
          port: 2181
        - host: zookeeper-1.zookeepers.clickhouse.svc.cluster.local
          port: 2181
        - host: zookeeper-2.zookeepers.clickhouse.svc.cluster.local
          port: 2181
      session_timeout_ms: 30000
      operation_timeout_ms: 10000
      root: /clickhouse
    
    users:
      default/password_sha256_hex:
        valueFrom:
          secretKeyRef:
            name: clickhouse-default-passwords
            key: password_sha256_hex
      default/networks/ip:
        - "::/0"
      default/profile: "default"
      default/access_management: 1
    
    settings:
      compression/case/method: "zstd"
      distributed_ddl/pool_size: 2
      distributed_ddl/task_max_lifetime: 300
      max_concurrent_queries: 100
      max_server_memory_usage_to_ram_ratio: 0.7
      background_pool_size: 16
      background_schedule_pool_size: 16
      background_merges_mutations_concurrency_ratio: 2

  defaults:
    templates:
      podTemplate: "clickhouse-pod-template"
      dataVolumeClaimTemplate: "data-volume-template"
      logVolumeClaimTemplate: "log-volume-template"
      serviceTemplate: "service-template"
  
  templates:
    podTemplates:
      - name: "clickhouse-pod-template"
        podDistribution:
          - type: ClickHouseAntiAffinity
            topologyKey: "kubernetes.io/hostname"
        spec:
          securityContext:
           fsGroup: 101
          
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:25.11
              imagePullPolicy: IfNotPresent
              securityContext:
                runAsUser: 101
                runAsGroup: 101
                fsGroup: 101
                runAsNonRoot: true
              
              resources:
                requests:
                  memory: "2Gi"
                  cpu: "512m"
                limits:
                  memory: "4Gi"
                  cpu: "1"
              
              # volumeMounts:
              #   - name: certs
              #     mountPath: /tmp/certs
              #     readOnly: true
              #   - name: config
              #     mountPath: /etc/clickhouse-server/config.d
              #     readOnly: true
              #   - name: cert-volume
              #     mountPath: /etc/clickhouse-server/certs
              
              livenessProbe:
                httpGet:
                  path: /ping
                  port: 8123
                  scheme: HTTP
                initialDelaySeconds: 30
                periodSeconds: 10
                timeoutSeconds: 5
                failureThreshold: 3
              
              readinessProbe:
                httpGet:
                  path: /ping
                  port: 8123
                  scheme: HTTP
                initialDelaySeconds: 10
                periodSeconds: 5
                timeoutSeconds: 3
                failureThreshold: 3
          
          # volumes:
          #   - name: certs
          #     secret:
          #       secretName: clickhouse-tls
          #       defaultMode: 0640
          #   - name: config
          #     configMap:
          #       name: clickhouse-config
          #   - name: cert-volume
          #     emptyDir: {}
    
    volumeClaimTemplates:
      - name: "data-volume-template"
        reclaimPolicy: Retain
        spec:
          storageClassName: longhorn 
          accessModes:              
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
      
      - name: "log-volume-template"
        reclaimPolicy: Retain
        spec:
          storageClassName: longhorn 
          accessModes:              
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
    
    serviceTemplates:
      - name: "service-template"
        generateName: "clickhouse-{chi}"
        metadata:
          labels:
            app: clickhouse
            cluster: cluster-ha
        spec:
          ports:
            - name: http
              port: 8123
              targetPort: 8123
              protocol: TCP
            - name: https
              port: 8443
              targetPort: 8443
              protocol: TCP
            - name: tcp
              port: 9000
              targetPort: 9000
              protocol: TCP
            - name: tcps
              port: 9440
              targetPort: 9440
              protocol: TCP
          type: ClusterIP
          sessionAffinity: ClientIP
