apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: clickhouse-operator-metrics
  namespace: clickhouse
  labels:
    app: clickhouse-operator
spec:
  selector:
    matchLabels:
      app: clickhouse-operator
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics