apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse-keeper
  namespace: clickhouse
  labels:
    app: clickhouse-keeper
spec:
  selector:
    matchLabels:
      app: clickhouse-keeper
  serviceName: clickhouse-keeper
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: clickhouse-keeper
    spec:
      # Run as clickhouse user (UID 101)
      securityContext:
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - clickhouse-keeper
              topologyKey: kubernetes.io/hostname
      initContainers:
        - name: fix-permissions
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              chown -R 101:101 /var/lib/clickhouse || true
              chmod -R 755 /var/lib/clickhouse || true
          volumeMounts:
            - name: data
              mountPath: /var/lib/clickhouse
          securityContext:
            runAsUser: 0
      containers:
        - name: clickhouse-keeper
          image: clickhouse/clickhouse-keeper:latest
          imagePullPolicy: IfNotPresent
          command:
          - /bin/bash
          - -c
          - |
            # Extract the index from the pod name (clickhouse-keeper-0 -> 0)
            INDEX=${HOSTNAME##*-}
            
            # Server ID is index + 1 (0 -> 1, 1 -> 2, 2 -> 3)
            export KEEPER_SERVER_ID=$((INDEX+1))
            
            echo "Starting ClickHouse Keeper"
            echo "Hostname: ${HOSTNAME}"
            echo "Server ID: ${KEEPER_SERVER_ID}"
            
            # Create log directory
            mkdir -p /var/log/clickhouse-keeper
            
            # Start keeper with the correct config path
            exec /usr/bin/clickhouse-keeper --config-file=/etc/clickhouse-keeper/keeper.xml --log-file=/var/log/clickhouse-keeper/clickhouse-keeper.log --errorlog-file=/var/log/clickhouse-keeper/clickhouse-keeper.err.log
          
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          ports:
            - containerPort: 9181
              name: client
            - containerPort: 9234
              name: raft
          volumeMounts:
            - name: data
              mountPath: /var/lib/clickhouse
            - name: config
              mountPath: /etc/clickhouse-keeper
          livenessProbe:
            tcpSocket:
              port: 9181
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - bash
                - -c
                - "echo ruok | nc localhost 9181 | grep -q imok"
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: config
          configMap:
            name: clickhouse-keeper-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn
        resources:
          requests:
            storage: 10Gi

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: clickhouse-keeper-pdb
  namespace: clickhouse
spec:
  selector:
    matchLabels:
      app: clickhouse-keeper
  maxUnavailable: 1