apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: zookeeper-metrics
  namespace: clickhouse
  labels:
    app: zookeeper
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: zookeeper
  podMetricsEndpoints:
    - port: prometheus
      interval: 30s
      path: /metrics