apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-clickhouse
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "2" 
  staleReplicaTimeout: "2880"