apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
spec:
  kafka:
    version: 4.1.0
    metadataVersion: 4.1-IV1
    # Use KRaft mode (no Zookeeper)
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      # Single node configurations
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      # Performance tuning for dev
      num.network.threads: 3
      num.io.threads: 8
      socket.send.buffer.bytes: 102400
      socket.receive.buffer.bytes: 102400
      socket.request.max.bytes: 104857600
      log.retention.hours: 168
      log.segment.bytes: 1073741824
      log.retention.check.interval.ms: 300000
  # No entity operator needed for dev (add manually if needed)
  entityOperator:
    topicOperator:
      watchedNamespace: kafka-dev  # or specific namespace
      reconciliationIntervalMs: 60000  # 60 seconds (default and recommended)
      resources:
        requests:
          memory: 512Mi
          cpu: 200m
        limits:
          memory: 512Mi
          cpu: 500m
      logging:
        type: inline
        loggers:
          rootLogger.level: INFO
    userOperator:
      watchedNamespace: kafka-dev  # or specific namespace
      reconciliationIntervalMs: 120000  # 120 seconds (recommended)
      resources:
        requests:
          memory: 512Mi
          cpu: 200m
        limits:
          memory: 512Mi
          cpu: 500m
      logging:
        type: inline
        loggers:
          rootLogger.level: INFO