apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: kafka-pool
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  replicas: 3
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 60Gi
        deleteClaim: false
        class: longhorn-kafka
        kraftMetadata: shared
  resources:
    requests:
      memory: 2Gi
      cpu: "500m"
    limits:
      memory: 4Gi
      cpu: "1"
  jvmOptions:
    "-Xms": "2Gi"   # Initial Heap Size
    "-Xmx": "2Gi"   # Max Heap Size
    "-XX":          # Advanced GC tuning (Optional)
      "UseG1GC": "true"
  
  template:
    pod:
      metadata:
        labels:
          environment: prod
      affinity: 
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: strimzi.io/cluster
                    operator: In
                    values:
                      - kafka-cluster
                  - key: strimzi.io/kind
                    operator: In
                    values:
                      - Kafka
                  - key: strimzi.io/name
                    operator: In
                    values:
                      - kafka-cluster-kafka-pool
              topologyKey: kubernetes.io/hostname
      tolerations:
        - key: "kafka"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      securityContext:
        runAsNonRoot: true
        fsGroup: 0