apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-kafka-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/geewynn/k8s-platform-infra.git
    targetRevision: HEAD
    path: infrastructure/strimzi/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  # Ignore operator-managed status fields
  ignoreDifferences:
    - group: kafka.strimzi.io
      kind: Kafka
      jsonPointers:
        - /status
    - group: kafka.strimzi.io
      kind: KafkaNodePool
      jsonPointers:
        - /status
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs